# ---------------------------
# KOALA project
# KidsWords and OZI vocabularies compared
# Thomas Klee
# Created: 2019-10-28
# Revised: 2019-10-29
# ---------------------------

# This script combines data from two sources
# and compares CDI word item from KidsWords and OZI.

# Note that only the vocabulary sections are compared.
# The two CDIs have other differences as well (e.g. grammar sections).

# load packages
library(tidyverse)

# "kidswords_item_data.csv" was generated by
# copying "cdi_lookup.csv" from the KidsWords data folder
# and selecting variables needed for the following analyses.

# load data files; wordbank data exported on 2019-10-28
OZI_items <- read_csv("data/OZI_item_data_wordbank.csv") 
KidsWords_items <- read_csv("data/kidswords_item_data.csv")

# add variable to each data frame to identify source dialect
OZI_items <- OZI_items %>%
  mutate(dialect = "AusEng")
KidsWords_items <- KidsWords_items %>%
  mutate(dialect = "NZEng")

# rename variables to make them consistent across CDIs ('new = old' format)
OZI_items <- rename(OZI_items, 
                    item = definition,
                    CDI_part = category)
KidsWords_items <- rename(KidsWords_items, item = CDI_item)

# select variables to compare
OZI_items <- OZI_items %>% 
  select(dialect, item, CDI_part)
KidsWords_items <- KidsWords_items %>%
  filter(field <= 22) %>% 
  select(dialect, item, CDI_part)

# merge data frames and alphabetise word item list
all_items <- full_join(KidsWords_items, OZI_items, by = "item")
all_items <- arrange(all_items,item)

# convert all word items to lower case
# needed for comparing case inconsistencies between CDIs
all_items$item <- str_to_lower(all_items$item)

# identify all words and indicate which CDI they occur on
print(all_items, n = Inf)

# identify words present on KidsWords but not OZI
onlyNZ <- all_items %>%
  filter(dialect.x == "NZEng" & is.na(dialect.y))
print(onlyNZ, n = Inf)

# identify words present on OZI but not Kidswords
onlyOZ <- all_items %>%
  filter(is.na(dialect.x) & dialect.y == "AusEng")
print(onlyOZ, n = Inf)

# identify words present on both CDIs
bothCDIs <- all_items %>%
  filter(dialect.x == "NZEng" & dialect.y =="AusEng")
print(bothCDIs, n = Inf)

# Note: 
# There are minor differences in the way word forms are represented 
# in the authors' original data files (e.g. OZI: baa baa, NZ: baa_baa; 
# OZI: all gone; NZ: allgone). I haven't cleaned these up although it 
# could be done if more accurate comparisons were needed.
