# ---------------------------
# KOALA project
# KidsWords and OZI vocabularies compared: xtable output
# Thomas Klee
# Created: 2019-10-30
# Revised: 
# ---------------------------

# This script produces output suitable for latex
# from data frames generated by koala_compareCDIs.R
# Could easily have been added to original script.

# load libraries
library(xtable)

print(xtable(onlyOZ, align = "rccccc"), booktabs = TRUE)

